spring:
  profiles:    active:    - dev
---
spring:  profiles: dev
  application: 
    name: microservicecloud-comfig-dev
    
---
spring:  profiles: test
  application:    name: microservicecloud-comfig-test